page_title="css:div.page-title"
old_pwd_txt="css:input#OldPassword"
new_pwd_txt="css:input#NewPassword"
confirm_new_pwd_txt="css:input#ConfirmNewPassword"
change_pwd_btn="xpath://button[contains(text(),'Change password')]"
bar_notification="xpath://div[@id='bar-notification']/div/p"
bar_notification_x_btn="css:span.close"
change_pwd_summary_errors="css:div.validation-summary-errors"
old_pwd_error="css:span#OldPassword-error"
new_pwd_error="css:span#NewPassword-error"
confirm_new_pwd_error="css:span#ConfirmNewPassword-error"